const TestConstansts = {
  LOAD_API_QUERY_QUERYBLOCKBYTRANSACTION:
    'LOAD_API_QUERY_QUERYBLOCKBYTRANSACTION',
  LOAD_API_QUERY_QUERYTXID: 'LOAD_API_QUERY_QUERYTXID',
  LOAD_API_QUERY_PAGING: 'LOAD_API_QUERY_PAGING',
};

export default TestConstansts;
